### ISSUE TITLE
after i go in the portal (server)

### ISSUE THREAD

**Issue by Exi36** [Mysticpasta1/Dimension-Atlantis#74]
[Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@2f8ba473, suppressing error
java.lang.ClassCastException: class com.mystic.atlantis.blocks.AtlantisClearPortalBlock cannot be cast to class net.minecraft.world.level.block.LiquidBlock (com.mystic.atlantis.blocks.AtlantisClearPortalBlock is in module atlantis@2023.1.22-1.19.2-1.3.1-forge of loader 'TRANSFORMER' @7462ba4b; net.minecraft.world.level.block.LiquidBlock is in module minecraft@1.19.2 of loader 'TRANSFORMER' @7462ba4b)
        at net.minecraftforge.fluids.FluidInteractionRegistry.handler$zlc000$immersiveWeatheringDataFluidInteraction(FluidInteractionRegistry.java:525) ~[forge-1.19.2-43.1.57-universal.jar%23342!/:?] {re:mixin,re:classloading,pl:mixin:A}
        at net.minecraftforge.fluids.FluidInteractionRegistry.canInteract(FluidInteractionRegistry.java) ~[forge-1.19.2-43.1.57-universal.jar%23342!/:?] {re:mixin,re:classloading,pl:mixin:A}
        at net.minecraft.world.level.block.LiquidBlock.m_6807_(LiquidBlock.java:110) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:immersive_weathering-common.mixins.json:LiquidBlockMixin,pl:mixin:APP:customportalapi.mixins.json:portalLighters.FluidBlockPlacedMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinLiquidBlock,pl:mixin:A}
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60696_(BlockBehaviour.java:686) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:snowrealmagic.mixins.json:BlockStateMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:canary.mixins.json:ai.pathing.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:block.flatten_states.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:chunk.block_counting.BlockStateBaseMixin,pl:mixin:APP:byg.mixins.json:common.block.MixinBlockBehaviourBlockStateBase,pl:mixin:APP:twigs.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:249) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,xf:fml:xaerominimap:xaero_chunkclass,xf:fml:xaeroworldmap:xaero_wm_chunkclass,re:classloading,xf:fml:xaerominimap:xaero_chunkclass,xf:fml:xaeroworldmap:xaero_wm_chunkclass,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelChunkMixin,pl:mixin:APP:leavesbegone.common.mixins.json:LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelChunkMixin,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_6933_(Level.java:211) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:biomemakeover-common.mixins.json:multipart.LevelMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_7731_(Level.java:188) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:biomemakeover-common.mixins.json:multipart.LevelMixin,pl:mixin:A}
        at net.minecraft.world.item.BucketItem.m_142073_(BucketItem.java:146) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,xf:fml:forge:bucketitem,re:classloading,xf:fml:forge:bucketitem,pl:mixin:APP:atlantis.mixins.json:BucketItemMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBucketItem,pl:mixin:A}
        at net.minecraft.world.item.BucketItem.m_7203_(BucketItem.java:90) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,xf:fml:forge:bucketitem,re:classloading,xf:fml:forge:bucketitem,pl:mixin:APP:atlantis.mixins.json:BucketItemMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBucketItem,pl:mixin:A}
        at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:266) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:canary.mixins.json:block.hopper.ItemStackMixin,pl:mixin:APP:canary.mixins.json:item.ItemStackMixin,pl:mixin:APP:biomemakeover-common.mixins.json:enchantment.ItemStackMixin,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:286) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:backpacked.mixins.json:common.PlayerInteractionManagerMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1089) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:classloading,re:mixin}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:computing_frames,re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
[12:03:06] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@cfbda9, suppressing error
java.lang.ClassCastException: class com.mystic.atlantis.blocks.AtlantisClearPortalBlock cannot be cast to class net.minecraft.world.level.block.LiquidBlock (com.mystic.atlantis.blocks.AtlantisClearPortalBlock is in module atlantis@2023.1.22-1.19.2-1.3.1-forge of loader 'TRANSFORMER' @7462ba4b; net.minecraft.world.level.block.LiquidBlock is in module minecraft@1.19.2 of loader 'TRANSFORMER' @7462ba4b)
        at net.minecraftforge.fluids.FluidInteractionRegistry.handler$zlc000$immersiveWeatheringDataFluidInteraction(FluidInteractionRegistry.java:525) ~[forge-1.19.2-43.1.57-universal.jar%23342!/:?] {re:mixin,re:classloading,pl:mixin:A}
        at net.minecraftforge.fluids.FluidInteractionRegistry.canInteract(FluidInteractionRegistry.java) ~[forge-1.19.2-43.1.57-universal.jar%23342!/:?] {re:mixin,re:classloading,pl:mixin:A}
        at net.minecraft.world.level.block.LiquidBlock.m_6807_(LiquidBlock.java:110) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:immersive_weathering-common.mixins.json:LiquidBlockMixin,pl:mixin:APP:customportalapi.mixins.json:portalLighters.FluidBlockPlacedMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinLiquidBlock,pl:mixin:A}
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60696_(BlockBehaviour.java:686) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:snowrealmagic.mixins.json:BlockStateMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:canary.mixins.json:ai.pathing.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:block.flatten_states.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:chunk.block_counting.BlockStateBaseMixin,pl:mixin:APP:byg.mixins.json:common.block.MixinBlockBehaviourBlockStateBase,pl:mixin:APP:twigs.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:249) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,xf:fml:xaerominimap:xaero_chunkclass,xf:fml:xaeroworldmap:xaero_wm_chunkclass,re:classloading,xf:fml:xaerominimap:xaero_chunkclass,xf:fml:xaeroworldmap:xaero_wm_chunkclass,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelChunkMixin,pl:mixin:APP:leavesbegone.common.mixins.json:LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelChunkMixin,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_6933_(Level.java:211) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:biomemakeover-common.mixins.json:multipart.LevelMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_7731_(Level.java:188) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:biomemakeover-common.mixins.json:multipart.LevelMixin,pl:mixin:A}
        at net.minecraft.world.item.BucketItem.m_142073_(BucketItem.java:146) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,xf:fml:forge:bucketitem,re:classloading,xf:fml:forge:bucketitem,pl:mixin:APP:atlantis.mixins.json:BucketItemMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBucketItem,pl:mixin:A}
        at net.minecraft.world.item.BucketItem.m_7203_(BucketItem.java:90) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,xf:fml:forge:bucketitem,re:classloading,xf:fml:forge:bucketitem,pl:mixin:APP:atlantis.mixins.json:BucketItemMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBucketItem,pl:mixin:A}
        at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:266) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:canary.mixins.json:block.hopper.ItemStackMixin,pl:mixin:APP:canary.mixins.json:item.ItemStackMixin,pl:mixin:APP:biomemakeover-common.mixins.json:enchantment.ItemStackMixin,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:286) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:backpacked.mixins.json:common.PlayerInteractionManagerMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1089) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:classloading,re:mixin}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:computing_frames,re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23337!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
        
        and this happend me at singleplayer:

The game crashed whilst exception ticking world
Error: java.lang.ClassCastException: null

**Comment by Mysticpasta1** [comment]
I need a modpack list:
And try it in Single Player btw itself and dependencies for it

**Comment by Exi36** [comment]
> 
[mods.txt](https://github.com/DimensionalDevelopment/atlantis/files/10474531/mods.txt)

in single player works but create portal is too a problem orb doesnt work to create  portal 
and server and single for me the cores dont activate it if i click right click on there 
i have to set   5x4 en in the corner above left i do a extra core in there and destroy him server and singleplayer crashed but after relogin portal works. but if i go in single in the portal all is good, in server also multiplayer crashes every time

**Comment by Mysticpasta1** [comment]
which version of mc, I only support 1.19.2 forge, for any other version talk to RedRoseWarrior on discord (see mod page)

**Comment by Exi36** [comment]
we have 1.19.2

**Comment by Mysticpasta1** [comment]
do you have the latest it just updated

**Comment by Mysticpasta1** [comment]
also the portal is a flat 4 by 4 filled with water and made with atlantean cores

**Comment by Mysticpasta1** [comment]
https://www.curseforge.com/minecraft/mc-mods/atlantis/files/4359405

**Comment by Mysticpasta1** [comment]
headed to bed I have been up all night and it is now 8:30 am CDT

**Comment by Exi36** [comment]
ok i have used the 1.3.1 i will try the 1.3.2 thank you alright good night :) its 3:52 pm here

**Comment by Exi36** [comment]
1.3.2 works thank you again for the fix
